spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/market_screener
        username: postgres
        password: password
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
market_screener:
    bot:
        username: BOT_USERNAME
        token: BOT_TOKEN
        settings:
            pump_threshold:
                min: 0.5
                max: 100.0
            dump_threshold:
                min: 0.5
                max: 100.0
            long_liquidation_threshold:
                min: 1000.0
                max: 100000.0
            short_liquidation_threshold:
                min: 1000.0
                max: 100000.0
    subscriber:
        default:
            pump_threshold: 1.0
            dump_threshold: 1.0
            long_liquidation_threshold: 5000.0
            short_liquidation_threshold: 5000.0
    screener:
        excluded: USDC, USTC, USDT, FDUSD, BTCST, BTCDOM, BTC, ETH, BCH, ETC, BNB, SOL, XRP, TON, DOGE, ADA, TRX, LTC, AVAX, SHIB, DOT, LINK, NEAR, MATIC, LEO, DAI, UNI, PEPE, KAS, ICP, FET, XMR, APT, RNDR, HBAR, XLM, ATOM, OKB, MNT, ARB, FIL, STX, CRO, IMX, MKR, XEM
        quote_asset: USDT
        threshold:
            pump: 0.5
            dump: 0.5
            long_liquidation: 1000.0
            short_liquidation: 1000.0
    chart:
        bar_count: 240
        bar_width: 6
        offset: 120
        interval: 1m
        line_stroke: 2, 4
        color:
            background: 20, 25, 35
            text: 170, 195, 215
            line: 105, 110, 120
            bull: 10, 150, 125
            bear: 230, 55, 70
        font:
            name: Liberation
            size: 18
